version: "3"
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL= postgresql://dharani722w8_user:cfIrj4OSU2CtbGJ6DfkCTTLBugxr855h@dpg-cronrlhu0jms73ccha60-a.oregon-postgres.render.com/dharani722w8

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL= postgresql://dharani722w8_user:cfIrj4OSU2CtbGJ6DfkCTTLBugxr855h@dpg-cronrlhu0jms73ccha60-a.oregon-postgres.render.com/dharani722w8